### ISSUE TITLE
Pre-transform error: "ESM integration proposal for Wasm" is not supported currently

### ISSUE THREAD

**Issue by CyberCactus** [AlansCodeLog/vectortracer#1]
Hi, I was trying this package in my angular test app (on MAC laptop), but after I implement your example, I'm getting the following error:

> 11:11:27 PM [vite] Pre-transform error: "ESM integration proposal for Wasm" is not supported currently. Use vite-plugin-wasm or other community plugins to handle this. Alternatively, you can use `.wasm?init` or `.wasm?url`. See https://vitejs.dev/guide/features.html#webassembly for more details.
> 11:11:27 PM [vite] Internal server error: "ESM integration proposal for Wasm" is not supported currently. Use vite-plugin-wasm or other community plugins to handle this. Alternatively, you can use `.wasm?init` or `.wasm?url`. See https://vitejs.dev/guide/features.html#webassembly for more details.

**Comment by alanscodelog** [comment]
If you're using vite you'll need to use vite-plugin-wasm, see it for how to configure it. It's pretty simple, you shouldn't need to configure anything special. If you're using it from a worker (recommended), you'll also need to add the web worker, it's also explained in the readme.

The reason this is needed is that the built code imports the wasm file itself (so one cannot add `?init/url` as the error suggests) and I would not want to add it since it's a builder specific syntax and also that code is auto-generated.

Am closing, but feel free to re-open if you still have issues.
